services:
  configurator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: "no"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    command:
      - "sh"
      - "-c"
      - |
        echo "Waiting for volume to be ready..."
        sleep 5
        echo "Creating common_site_config.json..."
        echo '{
          "redis_cache": "redis://redis-cache:6379",
          "redis_queue": "redis://redis-queue:6379",
          "redis_socketio": "redis://redis-socketio:6379"
        }' > /home/frappe/frappe-bench/sites/common_site_config.json
        echo "Config file created."
    networks:
      - erpnext-network

  # --- ZMĚNA V TÉTO SLUŽBĚ ---
  site-creator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: "no"
    depends_on:
      configurator:
        condition: service_completed_successfully
      mariadb:
        condition: service_started
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - SITE_NAME=${SITE_NAME}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
    command:
      - "sh"
      - "-c"
      - |
        # Zkontroluj, zda adresář stránky již existuje
        if [ -d "/home/frappe/frappe-bench/sites/${SITE_NAME}" ]; then
          echo "Site ${SITE_NAME} already exists, skipping creation."
          # Ukonči s úspěchem (exit 0), aby ostatní služby mohly pokračovat
          exit 0
        else
          echo "Site ${SITE_NAME} does not exist. Creating..."
          # Počkej na databázi a vytvoř stránku
          echo 'Waiting for database...' && sleep 30 && echo 'Starting site creation...' && \
          bench new-site ${SITE_NAME} --db-host ${MARIADB_HOST} --admin-password ${ADMIN_PASSWORD} --mariadb-root-username ${DB_ROOT_USER} --mariadb-root-password ${MYSQL_ROOT_PASSWORD} --install-app erpnext --set-default
        fi
  # --- KONEC ZMĚNY ---

  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_SITE_NAME_HEADER=${SITE_NAME}
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - BACKEND=erpnext-python:8000
      - SOCKETIO=frappe-socketio:9000
      - UPSTREAM_REAL_IP_ADDRESS=172.16.0.0/12
      - UPSTREAM_REAL_IP_HEADER=X-Forwarded-For
      - UPSTREAM_REAL_IP_RECURSIVE=on
    depends_on:
      site-creator:
        condition: service_completed_successfully
    ports:
      - "2284:80"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
    networks:
      - erpnext-network

  erpnext-python:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw
    networks:
      - erpnext-network

  frappe-socketio:
    image: frappe/frappe-socketio:${FRAPPE_VERSION}
    restart: on-failure
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
    networks:
      - erpnext-network

  erpnext-worker-default:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "worker"]
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
    networks:
      - erpnext-network

  erpnext-worker-short:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "worker"]
    environment:
      - WORKER_TYPE=short
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
    networks:
      - erpnext-network

  erpnext-worker-long:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "worker"]
    environment:
      - WORKER_TYPE=long
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
    networks:
      - erpnext-network

  erpnext-schedule:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "schedule"]
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
    networks:
      - erpnext-network

  redis-cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data
    networks:
      - erpnext-network

  redis-queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data
    networks:
      - erpnext-network

  redis-socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data
    networks:
      - erpnext-network

  mariadb:
    image: mariadb:10.6
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql
    networks:
      - erpnext-network

volumes:
  mariadb-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:
  assets-vol:
  sites-vol:
  logs-vol:

networks:
  erpnext-network:
    driver: bridge
