services:
  configurator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: "no"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites
    command:
      - "sh"
      - "-c"
      - |
        echo "Waiting for filesystems to be ready..."
        sleep 5
        echo "Creating common_site_config.json..."
        echo '{
          "redis_cache": "redis://redis-cache:6379",
          "redis_queue": "redis://redis-queue:6379",
          "redis_socketio": "redis://redis-socketio:6379"
        }' > /home/frappe/frappe-bench/sites/common_site_config.json
        echo "Config file created."

  site-creator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: "no"
    depends_on:
      configurator:
        condition: service_completed_successfully
      mariadb:
        condition: service_started
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SITE_NAME=${SITE_NAME}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
    command:
      - "sh"
      - "-c"
      - "echo 'Waiting for database to be ready...' && sleep 90 && echo 'Database should be ready, starting site creation...' && bench new-site ${SITE_NAME} --db-host ${MARIADB_HOST} --admin-password ${ADMIN_PASSWORD} --mariadb-root-username ${DB_ROOT_USER} --mariadb-root-password ${MYSQL_ROOT_PASSWORD} --install-app erpnext"

  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_SITE_NAME_HEADER=${SITE_NAME}
      - UPSTREAM_REAL_IP_ADDRESS=127.0.0.1
      - UPSTREAM_REAL_IP_HEADER=X-Forwarded-For
      - UPSTREAM_REAL_IP_RECURSIVE=on
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
    depends_on:
      erpnext-python:
        condition: service_started
      frappe-socketio:
        condition: service_started
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
    command:
      - "sh"
      - "-c"
      - "echo 'Waiting for backend services...' && sleep 15 && /docker-entrypoint.sh nginx -g 'daemon off;'"

  erpnext-python:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw

  frappe-socketio:
    image: frappe/frappe-socketio:${FRAPPE_VERSION}
    restart: on-failure
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-default:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "worker"]
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-short:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "worker"]
    environment:
      - WORKER_TYPE=short
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-long:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "worker"]
    environment:
      - WORKER_TYPE=long
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw

  erpnext-schedule:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: ["bench", "schedule"]
    depends_on:
      site-creator:
        condition: service_completed_successfully
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  redis-cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data

  mariadb:
    image: mariadb:10.6
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

volumes:
  mariadb-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:
  assets-vol:
  sites-vol:
  logs-vol:
